### ISSUE TITLE
Background image gets removed.

### ISSUE THREAD

**Issue by Steinthal** [andrie/reveal-auto-agenda#3]
@andrie, thanks for that extension. I'd like to add a background image to the agenda slide. I looked at the Lua script as well as the css file but my knowledge is too narrow to implement a background image on my own. Any chance you could add an option for a background image?

**Comment by andrie** [comment]
Thanks for reporting this.  I'll change this to a bug report.

It seems to me that the filter removes any background images.  I would have expected this example to add a background image, but it doesn't:

````
---
title: "Reveal auto-agenda"
subtitle: "Using the `reveal-auto-agenda` quarto extension to automatically create rolling agenda slides"
author: "Andrie de Vries"
format: revealjs
filters: 
  - reveal-auto-agenda
auto-agenda:
#   bullets: bullet
  heading: "Agenda:"
---

# Motivation {background-color="black" background-image="https://placekitten.com/100/100" background-size="100px" background-repeat="repeat"}

## Why? {background-color="black" background-image="https://placekitten.com/100/100" background-size="100px" background-repeat="repeat"}

To help people follow the logical flow of a presentation, it is useful to show all top level headings in a single agenda slide.

But it can be tedious to construct an agenda slide by hand, by copying all the top level headings.

This extension automatically constructs an agenda slide from the top level headings.

# Mechanics of `reveal-auto-agenda`

## Using the extension

Add this to the yaml header:

``` yaml
filters: 
  - reveal-auto-agenda
```

Then sit back and watch your agenda slide build itself.
````

**Comment by andrie** [comment]
I think the fix for this is to change the function definition for `change_header_class()` to this:

``` lua
local function change_header_class(el)
  el.attr.classes = {"agenda-slide"}
  return el
end
```

**Comment by andrie** [comment]
@Steinthal , can you please update your extension and report whether this fix works correctly?

**Comment by Steinthal** [comment]
> @Steinthal , can you please update your extension and report whether this fix works correctly?

Thanks for the prompt response, @andrie. Yes, the fix works as expected.
